/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

/**
 *
 * @author Nakahara Daiki
 */
public class formulario_Nueva_Pregunta extends javax.swing.JFrame {

    /**
     * Creates new form formulario_Nueva_Pregunta
     */
    public formulario_Nueva_Pregunta() {
        initComponents();
//        nueva_Pregunta objetoPregunta = pregunta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pregunta = new main.nueva_Pregunta();
        menuNuevaPregunta = new javax.swing.JMenuBar();
        itemNavegacion = new javax.swing.JMenu();
        ViajarAMenusPrincipal = new javax.swing.JMenuItem();
        ViajarANuevoTest = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        itemNavegacion.setText("Navegación");

        ViajarAMenusPrincipal.setText("Menú Principal");
        ViajarAMenusPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViajarAMenusPrincipalActionPerformed(evt);
            }
        });
        itemNavegacion.add(ViajarAMenusPrincipal);

        ViajarANuevoTest.setText("Empezar Test");
        ViajarANuevoTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViajarANuevoTestActionPerformed(evt);
            }
        });
        itemNavegacion.add(ViajarANuevoTest);

        menuNuevaPregunta.add(itemNavegacion);

        setJMenuBar(menuNuevaPregunta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViajarAMenusPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViajarAMenusPrincipalActionPerformed
        // TODO add your handling code here:
        //Nos movemos al menú principal
        new main_Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViajarAMenusPrincipalActionPerformed

    private void ViajarANuevoTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViajarANuevoTestActionPerformed
        // TODO add your handling code here:
        //Nos movemos a un nuevo test
        new test_Trivia().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ViajarANuevoTestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario_Nueva_Pregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario_Nueva_Pregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario_Nueva_Pregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario_Nueva_Pregunta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario_Nueva_Pregunta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ViajarAMenusPrincipal;
    private javax.swing.JMenuItem ViajarANuevoTest;
    private javax.swing.JMenu itemNavegacion;
    private javax.swing.JMenuBar menuNuevaPregunta;
    private main.nueva_Pregunta pregunta;
    // End of variables declaration//GEN-END:variables
}
