/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

//Imports necesarios para la conexión con la base de datos
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author Nakahara Daiki
 */
public class nueva_Pregunta extends javax.swing.JPanel {
    //Preparación para la conexión con la base de datos
    Connection connection = null;
    Statement statement = null;
    private Connection connect() {
        Connection conn = null;
        try{
            conn = DriverManager.getConnection("jdbc:sqlite:database.db");
        }catch (SQLException e) {
            System.err.println(e.getMessage());
        }
        return conn;
    }
    /**
     * Creates new form nueva_Pregunta
     */
    public nueva_Pregunta() {
        initComponents();
    }
    
    //Getters y Setters
    
    public String getPregunta() {
        return textPregunta.getText();
    }
    
    public void setPregunta (String pregunta){
        textPregunta.setText(pregunta);
    }
    
    public String getCorrecta() {
        return textCorrecta.getText();
    }
    
    public void setCorrecta (String correcta){
        textCorrecta.setText(correcta);
    }
    
    public String getErronea1() {
        return textErronea1.getText();
    }
    
    public void setErronea1 (String Erronea1){
        textErronea1.setText(Erronea1);
    }
    
    public String getErronea2() {
        return textErronea2.getText();
    }
    
    public void setErronea2 (String Erronea2){
        textErronea2.setText(Erronea2);
    }
    
    public String getErronea3() {
        return textErronea3.getText();
    }
    
    public void setErronea3 (String Erronea3){
        textErronea3.setText(Erronea3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textErronea1 = new javax.swing.JTextField();
        textErronea2 = new javax.swing.JTextField();
        textErronea3 = new javax.swing.JTextField();
        botonAceptar = new javax.swing.JButton();
        labelPregunta = new javax.swing.JLabel();
        labelCorrecta = new javax.swing.JLabel();
        labelErronea1 = new javax.swing.JLabel();
        labelErronea2 = new javax.swing.JLabel();
        labelErronea3 = new javax.swing.JLabel();
        textPregunta = new javax.swing.JTextField();
        textCorrecta = new javax.swing.JTextField();

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        labelPregunta.setText("Pregunta: ");

        labelCorrecta.setText("Respuesta Correcta:");

        labelErronea1.setText("Respuesta Incorrecta 1:");

        labelErronea2.setText("Respuesta Incorrecta 2:");

        labelErronea3.setText("Respuesta Incorrecta 3:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelPregunta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCorrecta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelErronea1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addComponent(textCorrecta)
                            .addComponent(textErronea1)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelErronea2)
                        .addGap(18, 18, 18)
                        .addComponent(textErronea2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelErronea3)
                        .addGap(18, 18, 18)
                        .addComponent(textErronea3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPregunta)
                    .addComponent(textPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCorrecta)
                    .addComponent(textCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelErronea1)
                    .addComponent(textErronea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelErronea2)
                    .addComponent(textErronea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelErronea3)
                    .addComponent(textErronea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(botonAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        // TODO add your handling code here:
        String empty = "";
        try {
            //Nos conectamos a la base de datos
            connection = this.connect();
            statement = connection.createStatement();
            statement.setQueryTimeout(20);
            //Insertamos los datos en la base
            String queryInsert = "INSERT INTO ListaPreguntas (Pregunta, Correcta, Erronea1, Erronea2, Erronea3) VALUES ('"+getPregunta()+"', '"+getCorrecta()+"', '"+getErronea1()+"', '"+getErronea2()+"', '"+getErronea3()+"')";
            statement.executeQuery(queryInsert);
        }
        catch(SQLException e) {
            System.err.println(e.getMessage());
        }
            //Limpiamos los cuadros de texto
            setPregunta(empty);
            setCorrecta(empty);
            setErronea1(empty);
            setErronea2(empty);
            setErronea3(empty);
    }//GEN-LAST:event_botonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JLabel labelCorrecta;
    private javax.swing.JLabel labelErronea1;
    private javax.swing.JLabel labelErronea2;
    private javax.swing.JLabel labelErronea3;
    private javax.swing.JLabel labelPregunta;
    private javax.swing.JTextField textCorrecta;
    private javax.swing.JTextField textErronea1;
    private javax.swing.JTextField textErronea2;
    private javax.swing.JTextField textErronea3;
    private javax.swing.JTextField textPregunta;
    // End of variables declaration//GEN-END:variables
}
