/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main;

/**
 *
 * @author Nakahara Daiki
 */
public class nuevo_Test extends javax.swing.JPanel {

    /**
     * Creates new form nuevo_Test
     */
    public nuevo_Test() {
        initComponents();
    }
    
    //Getters y Setters
    
    public String getPregunta() {
        return labelPregunta.getText();
    }
    
    public void setPregunta (String pregunta){
        labelPregunta.setText(pregunta);
    }
    
    public String getRadio1() {
        return radio1.getText();
    }
    
    public void setRadio1 (String radio){
        radio1.setText(radio);
    }
    
    public String getRadio2() {
        return radio2.getText();
    }
    
    public void setRadio2 (String radio){
        radio2.setText(radio);
    }
    
    public String getRadio3() {
        return radio3.getText();
    }
    
    public void setRadio3 (String radio){
        radio3.setText(radio);
    }
    
    public String getRadio4() {
        return radio4.getText();
    }
    
    public void setRadio4 (String radio){
        radio4.setText(radio);
    }
    
    //Getters para determinar si cierta opcion está marcada

    public boolean marcada1() {
        return radio1.isSelected();
    }
    
    public boolean marcada2() {
        return radio2.isSelected();
    }
    
    public boolean marcada3() {
        return radio3.isSelected();
    }
    
    public boolean marcada4() {
        return radio4.isSelected();
    }
    
    
    //Este setter dehabilita todas las respuestas para que no se puedan marcar
    public void disable(boolean statement) {
        radio1.setEnabled(statement);
        radio2.setEnabled(statement);
        radio3.setEnabled(statement);
        radio4.setEnabled(statement);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoRespuestas = new javax.swing.ButtonGroup();
        labelPregunta = new javax.swing.JLabel();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        radio4 = new javax.swing.JRadioButton();

        labelPregunta.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelPregunta.setText("• ¿Es esta una pregunta que no se debería ver bajo ningún concepto?");

        grupoRespuestas.add(radio1);
        radio1.setText("Sí");

        grupoRespuestas.add(radio2);
        radio2.setText("Jaja, sí");

        grupoRespuestas.add(radio3);
        radio3.setText("Yeah");

        grupoRespuestas.add(radio4);
        radio4.setText("Por favor, ayuda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelPregunta)
                .addGap(18, 18, 18)
                .addComponent(radio1)
                .addGap(18, 18, 18)
                .addComponent(radio2)
                .addGap(18, 18, 18)
                .addComponent(radio3)
                .addGap(18, 18, 18)
                .addComponent(radio4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoRespuestas;
    private javax.swing.JLabel labelPregunta;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    // End of variables declaration//GEN-END:variables
}
